### ISSUE TITLE
`SSH_CONNECTON` might be a typo

### ISSUE THREAD

**Issue by mvisat** [romkatv/windows-terminal-zsh-integration#1]
Hi, at this line:
https://github.com/romkatv/windows-terminal-zsh-integration/blob/9f69d06e9c534ba1e29310bbd74bc6b51eab78b2/windows-terminal-zsh-integration#L26

Do you mean `SSH_CONNECTION`?

**Comment by romkatv** [comment]
Thanks! Fixed.
